version: '3'
services:
  bitcoin_014:
    container_name: bitcoin_014
    image: ruimarinho/bitcoin-core:0.14-alpine
    ports:
      - 8432:8332
      - 8433:8333
      - 18432:18332
      - 18433:18333
    volumes:
      - ${SCRIPT_PATH}/blockchain/0.14/:/home/bitcoin/.bitcoin
    command: ${TESTNET} -printtoconsole -debug -prune=1024 -rpcbind=0.0.0.0
    depends_on:
      - bitcoin_015

  bitcoin_015:
    container_name: bitcoin_015
    image: ruimarinho/bitcoin-core:0.15-alpine
    ports:
      - 8332:8332
      - 8333:8333
      - 18332:18332
      - 18333:18333
    volumes:
      - ${SCRIPT_PATH}/blockchain/0.15/:/home/bitcoin/.bitcoin
    command: ${TESTNET} -printtoconsole -debug -rpcbind=0.0.0.0 -rpcallowip=172.16.0.0/12 -rpcallowip=172.17.0.0/16
    depends_on:
      - mongodb

  experiment:
    container_name: experiment
    build: ./experiment
    volumes:
     - ./data:/experiment/data
     - ./bitcoin.conf.015:/root/.bitcoin/bitcoin.conf
     - ./bitcoin.conf.014:/root/.bitcoin/bitcoin.conf.014
    environment:
     - MONGO_DB="mongodb://mongodb:27017"
     - TESTNET=${TESTNET}
  mongodb:
    container_name: mongodb
    image: mongo:3.4
    volumes:
     - ./db:/data/db
     - ./mongod.conf:/etc/mongod.conf
