version: '3'
services:
  reconstruct_mempool:
    build: .
    tty: true
    ports:
     - 8332:8332
     - 18332:18332
    volumes:
     - /home/huw/github/bitcoin:/bitcoin
     - .:/bitcoin-fee-to-latency
     - ./bitcoin.conf:/home/developer/.bitcoin/bitcoin.conf

  mongo:
    image: mongo:3.4
    volumes:
     - ./db:/data/db